name: autocheck

on:
  #手动运行
  workflow_dispatch:
  # 定时任务，在每天的11点自动运行
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      
      - name: get requirements
        run: |
          sudo apt-get install -y jq
          
      - name: getdata
        run: |
          sudo chmod +x getdata.sh
          ./getdata.sh

      - name: deal post method
        run: |
          source ./.config
          echo "TYPE=$post_type" >> $GITHUB_ENV
          
      - name: postdata(tg)
        env: 
          chat_id: ${{ secrets.CHAT_ID }}
          bot_token: ${{ secrets.BOT_TOKEN }}
        if: ${{ env.TYPE == 1 }}
        run: |
          sudo chmod +x tg.sh
          ./tg.sh
      - name: postdata(mail)
        if: ${{ env.TYPE == 2 }}
        env:
          mail_username: ${{ secrets.MAIL_USERNAME }}
          mail_password: ${{ secrets.MAIL_PASSWORD }}
          mail_add: ${{ secrets.INBOX }}
        run: |
          sudo apt install -y ssmtp mailutils
          sudo chmod +x setsmtp.sh
          ./setsmtp.sh
          sudo cp ssmtp.conf /etc/ssmtp/ssmtp.conf
          sudo cp revaliases /etc/ssmtp/revaliases
          sudo chmod +x mail.sh
          ./mail.sh
